# Setting the prefix from C-b to C-a
set -g prefix C-a

# Free the original Ctrl-b prefix keybinding
unbind C-b

bind Space send-prefix

set -g mouse on
set -s escape-time 0
set -g status on

# splitting panes with | and -
bind | split-window -h
bind ? split-window -v

bind h select-pane -L
bind l select-pane -R
bind j select-pane -D
bind k select-pane -U

# Select Layouts
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
bind -n M-a select-layout main-vertical
bind -n M-A select-layout main-horizontal 
bind -n M-E select-layout even-vertical
bind -n M-V select-layout even-horizontal

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
set -g pane-base-index 1

#――windows――――――――――――――――――――――――――――――――――――――
bind -n M-c new-window -c '#{pane_current_path}'
bind -n M-p previous-window
bind -n M-n next-window

#――Status-Bar―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
set-option -g status-style fg=black
# set-option -g status-style bg=grey
set-option -g status-style bg=black

set -g status-left "  #S"
set -g status-right "%Y-%b-%d  %R  "
set -g status-justify centre


# Set bind key to reload configuration file
bind r source-file ~/.tmux.conf \; display ​"Reloaded!"
