# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
#
# https://espanso.org/docs/matches/
#
#

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Month and date
  - trigger: ":md"
    replace: "{{monthdate}}"
    vars:
      - name: monthdate
        type: date
        params:
          format: "%m %d, %Y "
  
  # Dates
  - trigger: ":dd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d "

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
  # ===============================================
  # Signatures

  - trigger: ":te"
    replace: "Transform and Engage Team"

  - trigger: ":tl"
    replace: "http://teams.blabla.com\nhttp://communitypages.com\n"
  
  - trigger: ":br"
    replace: "Best Regards,\nAlf Nielsen\n"


  # ===============================================
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
    - name: output
      type: shell
      params:
        cmd: "curl 'https://api.ipify.org'"
        shell: zsh


  - trigger: ":quote"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "Every moment is a fresh beginning."
            - "Everything you can imagine is real."
            - "Whatever you do, do it well."


  - trigger: "fold newlines"
    replace: >
            this is really a
            single line of text
            despite appearances


  - trigger: "include newlines"
    replace: |
              exactly as you see
              will appear these three
              lines of poetry

  - trigger: ":div"
    replace: "<div>$|$</div>"



  - trigger: ":cat"
    image_path: "/path/to/image.png"


  - trigger: ":a"
    replace: "<a href='{{clipboard}}' />$|$</a>"
    vars:
      - name: "clipboard"
        type: "clipboard"


undo_backspace: true
show_notifications: false
