# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
#
# https://espanso.org/docs/matches/
#
#

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":dd"
    replace: "{{mydate}} "
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d "


  - trigger: ":ccopy"
    replace: "©"
 
  - trigger: ":ttm"
    replace: "™"

  - trigger: ":ip"
    replace: "ifconfig|grep 'inet ' \n "


  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}i" 

  # ===============================================
  #- trigger: ":ip"
  #  replace: "{{output}}"
  #  vars:
  #  - name: output
  #    type: shell
  #    params:
  #      cmd: "ifconfig|grep 'inet ' "
  #      shell: zsh


  - trigger: ":quote"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "Every moment is a fresh beginning."
            - "Everything you can imagine is real."
            - "Whatever you do, do it well."


  - trigger: "fold newlines"
    replace: >
            this is really a
            single line of text
            despite appearances


  - trigger: "include newlines"
    replace: |
              exactly as you see
              will appear these three
              lines of poetry

  - trigger: ":div"
    replace: "<div>$|$</div>"



  - trigger: ":cat"
    image_path: "/path/to/image.png"


  - trigger: ":aa"
    replace: "<a href='{{clipboard}}' />$|$</a>"
    vars:
      - name: "clipboard"
        type: "clipboard"


undo_backspace: false
show_notifications: false
