#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl # requires sa scripting
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp

# Override default layout for space 2 only
yabai -m config --space 2 layout float

# Default layout for spaces
yabai -m config top_padding                  55
yabai -m config bottom_padding               0
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   15

# Float windows
yabai -m rule --add app="^Spotify" manage=off
yabai -m rule --add app="^Wire" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Archive Utilities$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^BalenaEtchers$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Mail" manage=off
yabai -m rule --add app="^CleanMyMac" manage=off
yabai -m rule --add app="^VLC" manage=off
yabai -m rule --add app="^1Password" manage=off
yabai -m rule --add app="^IINA" manage=off
yabai -m rule --add app="^Calculator" manage=off
yabai -m rule --add app="^Terminal" manage=off

for_window [ title="notetaker_window" ] floating enable

echo "yabai configuration loaded..

