#!/bin/sh

echo -e "\e[1;32m ====================================================================== \e[0m "
echo " =========== Would you like to install zns dotfiles? (Y or N) ============"
echo " =========== This will overwrite existig zsh and .config files ==========="
echo -e "\e[1;32m ====================================================================== \e[0m "

read startinstall
# now check if $startinstall is "y"
if [ "$startinstall" = "y" ]; then

	echo "==========================================="
	echo "===== Retrieving dotfiles from github ====="
	echo "==========================================="

	git clone --depth=1 https://github.com/zestynotions/dotfiles.git
	chown $USER -R $HOME/dotfiles
	chmod -R 777 $HOME/dotfiles

	rm -rf $HOME/.config
	mv -f $HOME/dotfiles/.config $HOME/
	mv -f $HOME/dotfiles/.zshrc $HOME/.zshrc
	mv -f $HOME/dotfiles/.zshenv $HOME/.zshenv
	rm -rf $HOME/dotfiles

fi

echo ==========================================================================
echo -e "\e[1;32m All done! Enjoy :) \e[0m"
echo ==========================================================================
