# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true 

format = "$directory$git_status$character"
# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[∲=❯❯](bold fg:99)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[∲=❯❯](bold red)" 

[directory]
truncation_length = 5 
truncation_symbol = "…/"
style = "bold italic green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false 

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

